---
# Install Prometheus node-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- name: set internal variables for convenience
  set_fact:
    node_exporter_subdir: "{{ exporter_install_path }}/node_exporter-{{ node_exporter_version }}.linux-amd64"

- name: set download url for versions
  set_fact:
    node_exporter_tarball_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
  when: exporter_version

- name: set daemon dir for versions
  set_fact:
    node_exporter_daemon_dir: "{{ node_exporter_subdir }}"
  when: exporter_version

- name: download and untar node_exporter tarball
  unarchive:
    src: "{{ exporter_tarball_url }}"
    dest: "{{ exporter_install_path }}"
    copy: no

- name: create node-exporter group
  group: name={{ exporter_group }}  state=present

- name: create node-exporter user
  user:
    name: "{{ exporter_user }}"
    group: "{{ exporter_group }}"
    createhome: no
    shell: /sbin/nologin
    comment: "exporter User"
    state: present

- name: set permissions, owner and group
  file: path={{ exporter_daemon_dir }}/node_exporter owner={{ node_exporter_user }} group={{ node_exporter_group }} mode="go-w"

- name: set node_exporter variables
  copy: src="../files/etc-default-node_exporter"  dest=/etc/default/node_exporter
  register: exporter_config

- debug: var=exporter_config
  notify: reload node_exporter
  when: exporter_config.changed

- name: copy systemd config to server
  template: src="templates/node_exporter.service.j2"  dest="/lib/systemd/system/node_exporter.service"

- name: set status and start
  service: name=node_exporter enabled=yes state=started
